services:
  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Airflow
  airflow:
    build: ./airflow
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: ["standalone"]
    depends_on:
      - mongo

# docker-compose logs -f fastapi
  fastapi:
    build: ./fastapi
    container_name: fastapi_app2
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    depends_on:
      - mongo
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  spark_gateway:
    build: ./fastapi
    container_name: spark_gateway
    depends_on:
      - mongo
      - fastapi
    volumes:
      - ./fastapi:/app
    environment:
      - SOCKET_HOST=host.docker.internal
      - SOCKET_PORT=9999
    command: python /app/sparkGetWay.py

  streamlit:
    build: .
    container_name: streamlit_app
    depends_on:
      - mongo
      - airflow
      - fastapi
    ports:
      - "8501:8501"
    environment:
      MONGO_URI: mongodb://mongo:27017
      AIRFLOW_URL: http://airflow:8080

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_notebook
    depends_on:
      - mongo
      - fastapi
    ports:
      - "8888:8888"
    volumes:
      - C:/Users/aamir/Desktop/YC/P/SmartLogisticsAI:/home/jovyan/work
    environment:
      MONGO_URI: mongodb://mongo:27017
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/home/jovyan/work --allow-root --NotebookApp.token=''

volumes:
  mongo_data:
